### ISSUE TITLE
Remove abxLS replace it with abxLSPhon

### ISSUE THREAD

**Issue by nhamilakis** [zerospeech/benchmarks#12]
Following the updates, we did with Mark, i think the old abxLS module can be completely removed and replaced with the abxLSPhon one since it can do the same evaluation as the old one. 

The type of evaluation is decided on the  `context` parameter.

- **context: any** ⇒ will use the triphone item file and produce an abx2 style evaluation
- **context: within** ⇒ will use the phoneme item file and produce an abx1 style evaluation
- **context: all** ⇒ will use both the phoneme & triphone item files, call the ABX eval twice and produce both results.

Am i correct in my assumption ? i Would like your feedback @ewan @hallapmark 
Also, as Ewan said, maybe the benchmark name is not correct any more, should i change it to something else ?

**Comment by hallapmark** [comment]
Not exactly, but I am also not sure which level of abstraction we are talking about. I think it might help to distinguish between the labels and configurations used in the background in the abx2 code and the labels that are visible to the user of Benchmarks. 

Publicly/Benchmark user visible labels (proposal, probably Ewan would be the stakeholder to say what the best names are) and corresponding abx2 configurations : 

Context:
- **on-triphone** (abx1-style) evaluation ⇒ will use triphone item file and run abx2 within-context
- **within-context** evaluation ⇒ will use phoneme item file and run abx2 within-context
- **any-context** evaluation (alternatively we have also called it without-context) ⇒ will use phoneme item file and run abx2 any-context

All of these will run `speaker_mode=all`, i.e. there are separate scores for within speaker and across speaker for all these options.

Explanation: I think the source of the sort of taxonomic difficulty is that from the abx code's standpoint, the _on-triphone_ evaluation is also "within context", it is just that what is extracted are triphones along with the context, i.e. preceding and following phoneme, included (abc, where a and c are the fixed context). Whereas in the within-context on-phoneme evaluation, a and c are still the fixed context, but only b is extracted. This difference between the two "within" context options is caused _only_ by a difference in the timestamps in the item file. Literally, the old abx1 code could run _on-phoneme within context_ and _on-triphone within context_, if you make two calls with corresponding item files. Whereas for the any-context condition code changes were needed. 

I do not know how best to add a further layer of categorization and give the Benchmark user the option to run multiple of these at the same time. One option would be:

- **on-triphone AKA abx1-style evaluation** ⇒ run the **on-triphone** evaluation

- **on-phoneme AKA abx2-style evaluation** ⇒ run the **within-context** (phoneme item file) evaluation AND the **any-context** (phoneme item file) evaluation.

**Comment by ewan** [comment]
Yes, the two modules are functionally the same. The general name can be **abxLS** rather than **abxLSPhon**, even though we use the updated module.

Indeed, as @hallapmark indicates, there are two (mostly) independent dimensions, in addition to the **speaker** dimension, which means that the names **all** and **any** would be confusing. The first dimension is the *items*, which are either triphones are phones. The second is the *context* dimension, which can be either **within** or **any** (we sometimes also called this option **whatever** context, but we have been using). However, as you imply, it doesn't make much sense to run the triphone item file with the **any** option, therefore, we can do as Mark says and provide four options:

- **triphone**: triphone item file, within-context
- **phoneme-within**: phone item file, within-context
- **phoneme-any**: phone item file any-context
- **all**: run all four of the above

**Comment by nhamilakis** [comment]
I think i understand better now, i will modify my code accordingly

**Comment by nhamilakis** [comment]
After running the evaluation, the output in the Benchmark module looks something like this :

| subset     | speaker_mode | context_mode | granularity | score  | item_file                | pooling | seed |
|------------|--------------|--------------|-------------|--------|--------------------------|---------|------|
| dev-clean  | within       | within       | triphone    | 0.4932 | triphone-dev-clean.item  | none    | 3459 |
| dev-clean  | across       | within       | triphone    | 0.4981 | triphone-dev-clean.item  | none    | 3459 |
| dev-other  | within       | within       | triphone    | 0.4985 | triphone-dev-other.item  | none    | 3459 |
| dev-other  | across       | within       | triphone    | 0.4998 | triphone-dev-other.item  | none    | 3459 |
| test-clean | within       | within       | triphone    | 0.4970 | triphone-test-clean.item | none    | 3459 |
| test-clean | across       | within       | triphone    | 0.4996 | triphone-test-clean.item | none    | 3459 |
| test-other | within       | within       | triphone    | 0.4926 | triphone-test-other.item | none    | 3459 |
| test-other | across       | within       | triphone    | 0.5010 | triphone-test-other.item | none    | 3459 |
| dev-clean  | within       | within       | phoneme     | 0.5001 | phoneme-dev-clean.item   | none    | 3459 |
| dev-clean  | across       | within       | phoneme     | 0.4983 | phoneme-dev-clean.item   | none    | 3459 |
| dev-other  | within       | within       | phoneme     | 0.5136 | phoneme-dev-other.item   | none    | 3459 |
| dev-other  | across       | within       | phoneme     | 0.4994 | phoneme-dev-other.item   | none    | 3459 |
| test-clean | within       | within       | phoneme     | 0.5178 | phoneme-test-clean.item  | none    | 3459 |
| test-clean | across       | within       | phoneme     | 0.4979 | phoneme-test-clean.item  | none    | 3459 |
| test-other | within       | within       | phoneme     | 0.5000 | phoneme-test-other.item  | none    | 3459 |
| test-other | across       | within       | phoneme     | 0.4990 | phoneme-test-other.item  | none    | 3459 |
| dev-clean  | within       | any          | phoneme     | 0.5005 | phoneme-dev-clean.item   | none    | 3459 |
| dev-clean  | across       | any          | phoneme     | 0.5004 | phoneme-dev-clean.item   | none    | 3459 |
| dev-other  | within       | any          | phoneme     | 0.5044 | phoneme-dev-other.item   | none    | 3459 |
| dev-other  | across       | any          | phoneme     | 0.5002 | phoneme-dev-other.item   | none    | 3459 |
| test-clean | within       | any          | phoneme     | 0.4978 | phoneme-test-clean.item  | none    | 3459 |
| test-clean | across       | any          | phoneme     | 0.5000 | phoneme-test-clean.item  | none    | 3459 |
| test-other | within       | any          | phoneme     | 0.5027 | phoneme-test-other.item  | none    | 3459 |
| test-other | across       | any          | phoneme     | 0.4989 | phoneme-test-other.item  | none    | 3459 |

**Comment by hallapmark** [comment]
Yes, maybe the **item_file** column is redundant, **granularity** should be enough, but it's ok either way. Otherwise, this looks good to me!

**Comment by ewan** [comment]
This looks fine to me. I would keep the granularity column.
________________________________
