### ISSUE TITLE
abx17 does not run the English evaluations

### ISSUE THREAD

**Issue by ewan** [zerospeech/benchmarks#34]
Running the **abx17** evaluation as follows

```
zrc benchmarks:run abx17 ~/zr-data/samples/abx17-random-submission/
```

does not run the evaluations for the English subfolder, and passes directly to the French sets:

```
✔ Submission loaded successfully                                                                                               
✔ Submission Valid                                                                                                             
Loaded parameters from ➡ /home/emd/zr-data/samples/abx17-random-submission/params.yaml                                         
Running abx17 benchmark on abx17-random-submission                                                                             
==> Calculating abx distances for english_1s                                                                                   
==> Calculating abx distances for english_10s                                                                                  
==> Calculating abx distances for english_120s                                                                                 
==> Calculating abx distances for french_1s                                                                                    
  > Building the input features...   
...
```

This happens even though the item files are present in **zrc2017-test-dataset** and the feature files are present in **abx17-random-submission**.

**Comment by nhamilakis** [comment]
The abx17 uses the code from librispeech-abx to compute ABX scores, I have not performed many tests yet on if it works correctly, and i might have to migrate it to the old ABX module, i will look into it.

**Comment by ewan** [comment]
Is there a reason we can't use the abxLS code (would be exclusively triphone condition)? This might solve the issue by itself.
________________________________

**Comment by nhamilakis** [comment]
I just tested the abx17 evaluation of the random submission, and it works correctly on my laptop and on Oberon (with a fresh install).

I suspect your issue might come from the fact that the abx17 extension was not installed (forgot to add it into the '[all]' option) so if you did 'pip install zerospeech-benchmarks[all]' you might have missed it.

I pushed some updates to include it in the all flag, and to make the error message a bit clearer, now if the module is not installed the command writes a warning:  "abx17 extension not installed".

You should reinstall the module using the following command: 

```
pip install "zerospeech-benchmarks[all] @ git+https://github.com/zerospeech/benchmarks@master"
```

To get the latest version (i will push the updates to pip & conda registries, at some point during the day).

Once the module is updated & dependencies installed, run the following :

- `zrc datasets:pull zrc2017-test-dataset` or `zrc datasets:import zrc2017-test-dataset.zip` if you want to import it from the zip archive found [here](http://download.zerospeech.com/datasets/zrc2017-test-dataset.zip)
- `zrc samples:pull ` (i will add an import command for samples & checkpoints as well)
- `zrc benchmakrs:run abx17 /path/to/`

This should work, i cannot say anything about the accuracy of the computation though, we should probably do a comparison with previous scores (or maybe even use the ABXpy module if that makes the results comparable with the previously used ones).

If i need to do that, i would like some instructions and help, as i have never done something similar and don't know how i would go about doing such a comparison correctly. 


If this does not work, could you run the `zrc version`  and  `pip list` commands and post the output so i can see if your environment is correctly setup.

**Comment by ewan** [comment]
Yes, this works.

Yes, if this is the first time we run ABX17 with the new code base, we should re-run the submissions and compare them to the previous results. I believe the main barrier to doing that would be the old submissions. They will be in a different format, and some of them may have formatting issues (we did not have validation in ZR17). If you can confirm that they haven't been converted to the new format, then I will think about what the best time to do this is.

The "zrc datasets:pull" command is still experiencing issues with the checksum. However, everything works when the checksum validation is disabled.
________________________________

**Comment by nhamilakis** [comment]
I will check out, the submission format, if i remember correctly all submission were uploaded on zenodo (we might have a copy on Oberon).  

I am marking this issue as resolved, we can troubleshoot the checksum issue in #33.
