### ISSUE TITLE
Omission of context in the extraction of sets for running the ABX task

### ISSUE THREAD

**Issue by andrea08** [zerospeech/benchmarks#37]
When using `context: triphone-within` in the `params.yaml` file, the execution process calculates phoneme-within and phoneme-any contexts as well. In the eval call, the abx_sets are calculated, but that does not include the context specified in the `params.yaml` file. The problem comes already from the task.eval call that does not include the context explicitly.  
My suggestion would be to include the context from the submission object:

```
    abx_sets = self.extract_sets(submission, dataset, submission.params.context)
```

https://github.com/zerospeech/benchmarks/blob/9f1543f77ad744252e56831ba7829e3ab60bf856/zerospeech/tasks/abx/abxLS_phoneme/task.py#L121

**Comment by vectominist** [comment]
This issue is not resolved yet 🥲
