### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by hallapmark** [zerospeech/benchmarks#7]
The toolbox is officially supposed to run on Python 3.8, however currently it fails to run with Python 3.8. It appears the issue might be with type hinting syntax used that is only available from Python 3.9. 

To reproduce:
```
conda create -n py38test python=3.8
conda activate py38test
pip install zerospeech-libriabx2
pip install zerospeech-benchmarks[all]
zrc
```

The following error will appear in the trace:

```
/home/[username]/.conda/envs/py38test/lib/python3.8/site-packages/zerospeech/out.py", line 37, in DevNull
    def readlines(self, __hint: int = ...) -> list[AnyStr]:
TypeError: 'type' object is not subscriptable
```

The same error is NOT produced if, in the first step, one instead does 
`conda create -n py39test python=3.9`

Desired behavior:
Either the code should be fixed run with Python 3.8 or the required version should be increased to 3.9.

**Comment by nhamilakis** [comment]
The issue in with the type-hinting that uses `list` instead of `List`.
I think 3.8 can still be supported, as it is a recent (enough) version of python.
I will make the necessary fixes.
